version: '3'

services:
  postgres:
    container_name: market_db
    image: postgres:15
    restart: always
    environment:
      - POSTGRES_USER=${POSTGRES_USER}
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
      - POSTGRES_DB=${POSTGRES_DB}
    ports:
      - ${POSTGRES_PORT}:${POSTGRES_PORT}/tcp
  api:
    container_name: market_app
    env_file:
      - .env
    build: .
    profiles:
      - prod
    ports:
      - "8080:8080"
    depends_on:
      - postgres
    environment:
      - SPRING_DATASOURCE_URL=jdbc:postgresql://postgres:${POSTGRES_PORT}/${POSTGRES_DB}
      - SPRING_DATASOURCE_USERNAME=${POSTGRES_USER}
      - SPRING_DATASOURCE_PASSWORD=${POSTGRES_PASSWORD}
    command: -connectRetries=60
#  flyway:
#    container_name: market_flyway
#    environment:
#      - FLYWAY_USER=${POSTGRES_USER}
#      - FLYWAY_PASSWORD=${POSTGRES_PASSWORD}
#      - FLYWAY_URL=jdbc:postgresql://postgres:${POSTGRES_PORT}/${POSTGRES_DB}
#      - FLYWAY_GROUP=true
#    image: flyway/flyway:9
#    command: -locations=filesystem:/flyway/sql -connectRetries=60 migrate
#    volumes:
#      - /db/migration:/flyway/sql
#    depends_on:
#      - postgres